#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 17 23:58:47 2019

@author: linduri
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


dataset = pd.read_csv('Salary_data.csv')
dataset

X = dataset.iloc[:, 0:1].values
y= dataset.iloc[:, 1].values
y


# Splitting the dataset into the Training set and Test set
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

X.shape
y.shape

from sklearn.linear_model import LinearRegression
r=LinearRegression()
r.fit(X_train,y_train)
y_pred=r.predict(X_test)
y_pred

#Visualization Training sets
plt.scatter(X_train,y_train, color='blue')
plt.plot(X_train, r.predict(X_train), color='red')
plt.title('Salary Vs Experience')
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.show

#Visualization Test sets
plt.scatter(X_test,y_test, color='blue')
plt.plot(X_test, r.predict(X_test), color='red')
plt.title('Salary Vs Experience(Test Set)')
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.show

